name: Test Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job for Running Cypress Tests (UI and API)
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      # Update Node.js Actions to Use Newer Versions
      - name: Checkout repository
        uses: actions/checkout@v3  # Upgrade to v3 to address Node.js deprecation warnings

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Upgrade to v3 for Node 16/20 support
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npx cypress install  # Ensure Cypress binary is installed

      - name: Ensure Cypress Binary is Executable
        run: chmod +x $(npm bin)/cypress  # Fix permission issues with Cypress binary

      - name: Run Cypress tests
        run: npx cypress run
        continue-on-error: true  # Allow workflow to continue even if Cypress fails, to gather debug artifacts

      # Upload screenshots and videos if tests fail (using v4 for improved performance)
      - name: Upload Cypress screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ github.run_id }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ github.run_id }}
          path: cypress/videos
          if-no-files-found: ignore

  # Job for Running OWASP ZAP Security Scan
  zap-scan:
    name: Run OWASP ZAP Security Scan
    runs-on: ubuntu-latest

    steps:
      # Update Node.js Actions to Use Newer Versions
      - name: Checkout repository
        uses: actions/checkout@v3  # Upgrade to v3 to address Node.js deprecation warnings

      # Check Docker Installation to Ensure It's Available
      - name: Check Docker Installation
        run: docker --version

      - name: Run OWASP ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.4.0  # Updated to v0.4.0 to support newer Node.js versions
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false  # Allow the workflow to continue even if vulnerabilities are found

      # Upload ZAP report as artifact
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report-${{ github.run_id }}
          path: /zap/wrk/*.html




