name: Full Test Suite Workflow

permissions:
  contents: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Mocha Reporter
        run: npm install mocha-junit-reporter

      - name: Install Cypress Globally
        run: npm install -g cypress

      - name: Ensure Cypress Binary is Executable
        run: sudo chmod +x $(npm bin)/cypress

      - name: Run Cypress Tests with Debug
        run: DEBUG=cypress:* npx cypress run --reporter mocha-junit-reporter --reporter-options mochaFile=results/test-results-[hash].xml --retries 2
        continue-on-error: true

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ github.run_id }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ github.run_id }}
          path: cypress/videos
          if-no-files-found: ignore

  codeql-analysis:
    name: Run CodeQL Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up CodeQL
        uses: github/codeql-action/init@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
