name: tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-tests:
    name: Run Cypress Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Upgrade to v4 to ensure Node.js compatibility

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Upgrade to v4 for Node.js 20 compatibility
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Install Cypress Globally
        run: npm install -g cypress

      - name: Ensure Cypress Binary is Executable
        run: sudo chmod +x $(npm bin)/cypress

      - name: Run Cypress Tests
        run: npx cypress run
        continue-on-error: true  # Continue the workflow to gather artifacts even if tests fail

      - name: Upload Cypress Screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots-${{ github.run_id }}
          path: cypress/screenshots
          if-no-files-found: ignore

      - name: Upload Cypress Videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos-${{ github.run_id }}
          path: cypress/videos
          if-no-files-found: ignore

  zap-scan:
    name: Run OWASP ZAP Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4  # Upgrade to v4 for better compatibility

      # Step to Check Docker Installation Status
      - name: Check Docker Installation
        run: docker --version

      # Managed OWASP ZAP Action without Explicit Docker Handling
      - name: Run OWASP ZAP Live Scan
        uses: zaproxy/action-full-scan@v0.5.0  # Try using a different version or type of scan
        with:
          target: 'https://thinking-tester-contact-list.herokuapp.com/'  # Replace with your application URL
          token: ${{ secrets.GITHUB_TOKEN }}
          fail_action: false  # Allow the workflow to proceed even if vulnerabilities are found

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: /zap/wrk/*.html

